### ISSUE TITLE
Add progress bar

### ISSUE THREAD

**Issue by juancri** [juancri/covid19-animation-generator#21]

**Comment by juancri** [comment]
This is a nice to have. A progress bar for the console so we can know the state of the process.

**Comment by kalilinuxvirtual** [comment]
whow to write states separately eg los angeles in the terminal

**Comment by juancri** [comment]
> whow to write states separately eg los angeles in the terminal

This comment doesn't seem to be related with this issue. Please open a new issue, if necessary.

**Comment by juancri** [comment]
Done
