### ISSUE TITLE
Test por día

### ISSUE THREAD

**Issue by karladatt** [juancri/covid19-animation-generator#31]
Hola, muchas gracias por tu página. ¿es posible realizar un gráfico con la comparación de los test realizados por día en distintos países?

**Comment by juancri** [comment]
Hola! Gracias por la sugerencia. Por ahora, en los issues solo hay tracking de errores o features del software. Puedes encontrar las preguntas frecuentes [aquí](https://github.com/juancri/covid19-animation-generator/wiki/FAQ-Chile) y dejar sugerencias de nuevos gráficos [aquí](https://docs.google.com/forms/d/e/1FAIpQLSd7vjttj5S6nODfrpfE59Khs7B5TMLN272yF7cTcxPcfTvahg/viewform).
