### ISSUE TITLE
Running COVID-19 Animation Generator as a service

### ISSUE THREAD

**Issue by 4tikhonov** [juancri/covid19-animation-generator#42]
HI @juancri, it's very interesting app that you're working on, congratulations!

I'm wondering if you're interested to have more data in it and run as a service for our http://github.com/CoronaWhy community. We have some Cloud and resources to support projects like yours and building a Common Data and Research Infrastructure for COVID-19 researchers https://github.com/CoronaWhy/coronawhy-infrastructure

**Comment by juancri** [comment]
Hi, @4tikhonov!

Your project seems very interesting. Sadly, I currently don't have capacity to integrate the animation software. Anyway, feel free to use it in any way and let me know if you find any issues.

JC

**Comment by 4tikhonov** [comment]
Thanks @juancri. I was thinking to connect your animation to the historical datasets on Spanish flu pandemic happened a hundred years ago, we have collected some data on it http://datasets.coronawhy.org/dataverse/pandemics

We have some resources to do that, can I communicate with you in this issue here and send here our developers if they have some questions?

**Comment by juancri** [comment]
For sure. Feel free to reach me here if you need help or if you have any suggestions.

**Comment by juancri** [comment]
Closing for now. Please feel free to open a new issue if necessary.
