### ISSUE TITLE
Available beds per region

### ISSUE THREAD

**Issue by juancri** [juancri/covid19-animation-generator#57]

**Comment by juancri** [comment]
We need to monitor these sources:

https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto52
https://github.com/MinCiencia/Datos-COVID19/tree/master/output/producto58

They have not been updated for 2 weeks

**Comment by dna33** [comment]
updated

**Comment by juancri** [comment]
@dna33, thanks! Already publishing graphs for this:
https://twitter.com/hashtag/GraficoCovid042?src=hashtag_click

Resolving.
