### ISSUE TITLE
Qué comando ejecutas para sacar un gráfico?

### ISSUE THREAD

**Issue by lfalvarez** [juancri/covid19-animation-generator#63]
Estuve intentando correr un gráfico con el código, pero me escribe todos los frames de un video en la carpeta `output`. Sin embargo, si a mi sólo me gustaría ver el último día, cómo le hago?

Bacán el proyecto BTW 😄

**Comment by juancri** [comment]
Hola! Gracias. Puedes usar el parámetro `--sample` que produce solo un frame del último día y el cover. Puedes reabrir este issue si tienes algún problema o sugerencia.
